swagger: "2.0"
info:
  version: 1.1.0
  title: IO API for administration purpose
  contact:
    name: Digital Transformation Team
    url: https://forum.italia.it/c/progetto-io
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg
  description: >
    # Warning

    **This is an experimental API that is (most probably) going to change as we evolve the IO platform.**

    # Introduction

    This is the documentation of the IO API for administration purpose of the platform.

host: api.cd.italia.it
basePath: "/onboarding"
schemes:
  - https
security:
  - SubscriptionKey: []
paths:
  "/test/{test_id}":
    parameters:
      - name: test_id
        in: path
        type: string
        required: true
        description: test id.
    get:
      operationId: getService
      summary: Get Service
      description: A previously created service with the provided service ID is returned.
      responses:
        "200":
          description: Service found.
          schema:
            "$ref": "#/definitions/Test"
          examples:
            application/json:
              id: 2b3e728c1a5d1efa035c-0000000000000001
              test: ale
        "401":
          description: Unauthorized
        "404":
          description: No service found for the provided ID.
      parameters: []
definitions:
  Test:
    type: object
    properties:
      id:
        type: string
      test: 
        type: string
